---
title: "lab_exersice#1_Echaveria"
author: "Luigi Echaveria"
date: "2024-02-12"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Scraping for Pillows

```{r}

#install.packages("dplyr")
#install.packages("rvest")
#install.packages("polite")
#install.packages("httr")

library(dplyr)
library(rvest)
library(polite)
library(httr)
```

```{r}
pillows_products <- data.frame()
```

```{r}
pillowslink1 = "https://www.amazon.co.uk/s?k=pillows&crid=2K83RHGWXZFI7&sprefix=pillow%2Caps%2C1371&ref=nb_sb_noss_1"

session1 <- bow(pillowslink1,
           user_agent = "For Educational Purpose")
```

```{r}
scrapeNodes <- function(selector){
scrape(session) %>%
  html_nodes(selector) %>%
  html_text(trim = TRUE)
}
```

```{r}
scrapedCategory <- "Pillows"
scrapeName <- "Pillows"
```

```{r}
scrapedName <- scrapeNodes(".s-featured-result-item span.a-size-base-plus, .s-widget-container > span span.a-size-base-plus")
scrapedpillowsName <- scrapedpillowsName[1:45]

scrapedPrice <- scrapeNodes(".s-featured-result-item .a-size-base div.a-row:nth-of-type(1), .s-widget-container > span .a-row div.a-row:nth-of-type(1)")
scrapedpillowsPrice <- scrapedpillowsPrice[1:45]

scrapedRatings <- scrapeNodes(".s-featured-result-item div.a-spacing-top-micro:nth-of-type(n+2) div.a-size-small, .s-widget-container > span div.a-spacing-top-micro:nth-of-type(n+2) div.a-size-small")
scrapedpillowsRatings <- scrapedpillowsRatings[1:45]

scrapedReviews <- scrapeNodes("span.a-size-base.s-underline-text")
scrapedpillowsReviews <- scrapedpillowsReviews[1:45]

pillows_products <- rbind(pillows_products, data.frame(category = scrapedCategory,name = scrapedName,
                    price = scrapedPrice,
                    ratings = scrapedRatings,
                    no_of_reviews = scrapedReviews))
```

```{r}

pillowslink2 = "https://www.amazon.co.uk/s?k=pillows&page=2&crid=2K83RHGWXZFI7&qid=1707732484&sprefix=pillow%2Caps%2C1371&ref=sr_pg_2"
session2 <- bow(pillowslink2,
           user_agent = "For Educational Purpose")
```

```{r}
scrapedCategory2 <- "Pillows"
```

```{r}
scrapedpillowsName2 <- scrapeNodes("h2.a-size-mini.a-spacing-none.a-color-base.s-line-clamp-4")
scrapedpillowsName2 <- scrapedpillowsName2[1:45]

scrapedpillowsPrice2 <- scrapeNodes("span.a-offscreen")
scrapedpillowsPrice2 <- scrapedpillowsPrice2[1:45]

scrapedpillowsRatings2 <- scrapeNodes("span.a-icon-alt")
scrapedpillowsRatings2 <- scrapedpillowsRatings2[1:45]

scrapedpillowsReviews2 <- scrapeNodes("span.a-size-base.s-underline-text")
scrapedpillowsReviews2 <- scrapedpillowsReviews2[1:45]
```

```{r}

pillows_products <- rbind(pillows_products, data.frame(category = scrapedCategory,name = scrapedName,
                    price = scrapedPrice,
                    ratings = scrapedRatings,
                    no_of_reviews = scrapedReviews))

```

```{r}
pillowslink3 = "https://www.amazon.co.uk/s?k=pillows&page=3&crid=2K83RHGWXZFI7&qid=1707732557&sprefix=pillow%2Caps%2C1371&ref=sr_pg_3"

session3 <- bow(pillowslink3,
           user_agent = "For Educational Purpose")

scrapedCategory3 <- "Pillows"

scrapedpillowsName3 <- scrapeNodes("h2.a-size-mini.a-spacing-none.a-color-base.s-line-clamp-4")
scrapedpillowsName3 <- scrapedpillowsName3[1:45]

scrapedpillowsPrice3 <- scrapeNodes("span.a-offscreen")
scrapedpillowsPrice3 <- scrapedpillowsPrice3[1:45]

scrapedpillowsRatings3 <- scrapeNodes("span.a-icon-alt")
scrapedpillowsRatings3 <- scrapedpillowsRatings3[1:45]

scrapedpillowsReviews3 <- scrapeNodes("span.a-size-base.s-underline-text")
scrapedpillowsReviews3 <- scrapedpillowsReviews3[1:45]

pillows_products <- rbind(pillows_products, data.frame(category = scrapedCategory,name = scrapedName,
                    price = scrapedPrice,
                    ratings = scrapedRatings,
                    no_of_reviews = scrapedReviews))

pillows_products <- pillows_products[1:100,]


#View(pillows_products)
```

```{r}
library(dplyr)
library(rvest)
library(polite)
library(httr)
```

```{r}

socks_products <- data.frame()

sockslink1 = "https://www.amazon.co.uk/s?k=socks&crid=2MKL0KHSTUZXS&sprefix=socks%2Caps%2C565&ref=nb_sb_noss_1"

session4 <- bow(sockslink1,
           user_agent = "For Educational Purpose")

scrapeNodes <- function(selector){
scrape(session) %>%
  html_nodes(selector) %>%
  html_text(trim = TRUE)
}

scrapedCategory4 <- "Socks"

scrapedsocksName <- scrapeNodes("h2.a-size-mini.a-spacing-none.a-color-base.s-line-clamp-4")
scrapedsocksName <- scrapedsocksName[1:45]

scrapedsocksPrice <- scrapeNodes("span.a-offscreen")
scrapedsocksPrice <- scrapedsocksPrice[1:45]

scrapedsocksRatings <- scrapeNodes("span.a-icon-alt")
scrapedsocksRatings <- scrapedsocksRatings[1:45]

scrapedsocksReviews <- scrapeNodes("span.a-size-base.s-underline-text")
scrapedsocksReviews <- scrapedsocksReviews[1:45]



socks_products <- rbind(socks_products, data.frame(category = scrapedCategory4,name = scrapedsocksName,
                    price = scrapedsocksPrice,
                    ratings = scrapedsocksRatings,
                    no_of_reviews = scrapedsocksReviews))
```

```{r}
sockslink2 = "https://www.amazon.co.uk/s?k=socks&page=2&crid=2MKL0KHSTUZXS&qid=1707733227&sprefix=socks%2Caps%2C565&ref=sr_pg_2"

session5 <- bow(sockslink2,
           user_agent = "For Educational Purpose")

scrapeNodes <- function(selector){
scrape(session) %>%
  html_nodes(selector) %>%
  html_text(trim = TRUE)
}

scrapedCategory5 <- "Socks"

scrapedsocksName2 <- scrapeNodes("h2.a-size-mini.a-spacing-none.a-color-base.s-line-clamp-4")
scrapedsocksrName2 <- scrapedsocksName2[1:45]

scrapedsocksPrice2 <- scrapeNodes("span.a-offscreen")
scrapedsocksPrice2 <- scrapedsocksPrice2[1:45]

scrapedsocksRatings2 <- scrapeNodes("span.a-icon-alt")
scrapedsocksRatings2 <- scrapedsocksrRatings2[1:45]

scrapedsocksReviews2 <- scrapeNodes("span.a-size-base.s-underline-text")
scrapedsocksReviews2 <- scrapedsocksReviews2[1:45]



socks_products <- rbind(socks_products, data.frame(category = scrapedCategory5,name = scrapedsocksName2,
                    price = scrapedsocksPrice2,
                    ratings = scrapedsocksrRatings2,
                    no_of_reviews = scrapedsocksReviews2))
```

```{r}
sockslink3 = "https://www.amazon.co.uk/s?k=socks&page=3&crid=2MKL0KHSTUZXS&qid=1707733812&sprefix=socks%2Caps%2C565&ref=sr_pg_2"

session6 <- bow(sockslink3,
           user_agent = "For Educational Purpose")

scrapeNodes <- function(selector){
scrape(session) %>%
  html_nodes(selector) %>%
  html_text(trim = TRUE)
}

scrapedCategory6 <- "Sharpener"

scrapedsocksrName3 <- scrapeNodes("h2.a-size-mini.a-spacing-none.a-color-base.s-line-clamp-4")
scrapedsocksName3 <- scrapedsocksName3[1:45]

scrapedsocksPrice3 <- scrapeNodes("span.a-offscreen")
scrapedsocksPrice3 <- scrapedsocksPrice3[1:45]

scrapedsocksRatings3 <- scrapeNodes("span.a-icon-alt")
scrapedsocksRatings3 <- scrapedsocksRatings3[1:45]

scrapedsocksrReviews3 <- scrapeNodes("span.a-size-base.s-underline-text")
scrapedsocksReviews3 <- scrapedsocksrReviews3[1:45]



socks_products <- rbind(socks_products, data.frame(category = scrapedCategory5,name = scrapedsocksrName2,
                    price = scrapedsocksrPrice2,
                    ratings = scrapedsocksRatings2,
                    no_of_reviews = scrapedsocksReviews2))

socks_products <- socks_products[1:100,]


#View(socks_products)
```
Merging Two Products
```{r}
scraped_products <- rbind(pillows_products, socks_products)
View(scraped_products)
```

10 PRODUCTS

product1

```{r}

library(dplyr)
library(rvest)
library(polite)
library(httr)
library(selectr)

product1 = data.frame()
scrapedCategory <- "Pillows"
  
  link = "https://www.amazon.co.uk/product-reviews/B01FMHF1EA/ref=acr_search_hist_5?ie=UTF8&filterByStar=five_star&reviewerType=all_reviews#reviews-filter-bar"
  
      sessionProd1 <- bow(link,
               user_agent = "For Educational Purpose")
  
      scrapeNodes <- function(selector){
      scrape(sessionProd1) %>%
        html_nodes(selector) %>%
        html_text(trim = TRUE)
      }
          
      scrapedprodName <- scrapeNodes("h1.a-size-large.a-text-ellipsis")
    
      
      scrapedReviewer <- scrapeNodes("span.a-profile-name")
      scrapedReviewer <- scrapedReviewer[1:10]

      
      scrapedReview <- scrapeNodes("span.a-size-base.review-text.review-text-content")
      scrapedReview <- scrapedReview[1:10]

      
      scrapedDate <- scrapeNodes("span.a-size-base.a-color-secondary.review-date")
      scrapedDate <- scrapedDate[1:10]

      
      scrapedprodRating <- scrapeNodes("span.a-icon-alt")
      scrapedprodRating <- scrapedprodRating[1:10]

      
      product1 <- rbind(product1, data.frame(category = scrapedCategory,name = scrapedprodName,
                          reviewer = scrapedReviewer,
                          review = scrapedReview,
                          date = scrapedDate,
                         ratings = scrapedprodRating))
```

```{r}
link2 = "https://www.amazon.co.uk/product-reviews/B01FMHF1EA/ref=cm_cr_arp_d_paging_btm_next_2?ie=UTF8&filterByStar=five_star&reviewerType=all_reviews&pageNumber=2#reviews-filter-bar"
  
  sessionProd2 <- bow(link2,
               user_agent = "For Educational Purpose")


      scrapedReviewer2 <- scrapeNodes("span.a-profile-name")
      scrapedReviewer2 <- scrapedReviewer2[1:10]

      
      scrapedReview2 <- scrapeNodes("span.a-size-base.review-text.review-text-content")
      scrapedReview2 <- scrapedReview2[1:10]

      
      scrapedDate2 <- scrapeNodes("span.a-size-base.a-color-secondary.review-date")
      scrapedDate2 <- scrapedDate2[1:10]

      
      scrapedprodRating2 <- scrapeNodes("span.a-icon-alt")
      scrapedprodRating2 <- scrapedprodRating2[1:10]

      
      product1 <- rbind(product1, data.frame(category = scrapedCategory ,name = scrapedprodName,
                          reviewer = scrapedReviewer2,
                          review = scrapedReview2,
                          date = scrapedDate2,
                         ratings = scrapedprodRating2))
```

```{r}
  link3 = "https://www.amazon.co.uk/product-reviews/B01FMHF1EA/ref=cm_cr_getr_d_paging_btm_next_3?ie=UTF8&filterByStar=five_star&reviewerType=all_reviews&pageNumber=3#reviews-filter-bar"
  
  sessionProd3 <- bow(link3,
               user_agent = "For Educational Purpose")


      
      scrapedReviewer3 <- scrapeNodes("span.a-profile-name")
      scrapedReviewer3 <- scrapedReviewer3[1:10]

      
      scrapedReview3 <- scrapeNodes("span.a-size-base.review-text.review-text-content")
      scrapedReview3 <- scrapedReview3[1:10]

      
      scrapedDate3 <- scrapeNodes("span.a-size-base.a-color-secondary.review-date")
      scrapedDate3 <- scrapedDate3[1:10]

      
      scrapedprodRating3 <- scrapeNodes("span.a-icon-alt")
      scrapedprodRating3 <- scrapedprodRating3[1:10]

      
      product1 <- rbind(product1, data.frame(category = scrapedCategory ,name = scrapedprodName,
                          reviewer = scrapedReviewer3,
                          review = scrapedReview3,
                          date = scrapedDate3,
                         ratings = scrapedprodRating3))
      
View(product1)
```

product2

```{r}

library(dplyr)
library(rvest)
library(polite)
library(httr)
library(selectr)

product2 = data.frame()
scrapedCategory <- "Pillows"
```

```{r}
 link = "https://www.amazon.co.uk/product-reviews/B006DDGCI2/ref=acr_search_hist_5?ie=UTF8&filterByStar=five_star&reviewerType=all_reviews#reviews-filter-bar"
  
      sessionProd1 <- bow(link,
               user_agent = "For Educational Purpose")
  
      scrapeNodes <- function(selector){
      scrape(sessionProd1) %>%
        html_nodes(selector) %>%
        html_text(trim = TRUE)
      }
          
      scrapedprodName <- scrapeNodes("h1.a-size-large.a-text-ellipsis")
    
      
      scrapedReviewer <- scrapeNodes("span.a-profile-name")
      scrapedReviewer <- scrapedReviewer[1:10]

      
      scrapedReview <- scrapeNodes("span.a-size-base.review-text.review-text-content")
      scrapedReview <- scrapedReview[1:10]

      
      scrapedDate <- scrapeNodes("span.a-size-base.a-color-secondary.review-date")
      scrapedDate <- scrapedDate[1:10]

      
      scrapedprodRating <- scrapeNodes("span.a-icon-alt")
      scrapedprodRating <- scrapedprodRating[1:10]

      
      product2 <- rbind(product2, data.frame(category = scrapedCategory,name = scrapedprodName,
                          reviewer = scrapedReviewer,
                          review = scrapedReview,
                          date = scrapedDate,
                         ratings = scrapedprodRating))
```

```{r}
link2 = "https://www.amazon.co.uk/product-reviews/B006DDGCI2/ref=cm_cr_arp_d_paging_btm_next_2?ie=UTF8&filterByStar=five_star&reviewerType=all_reviews&pageNumber=2#reviews-filter-bar"
  
  sessionProd2 <- bow(link2,
               user_agent = "For Educational Purpose")


      scrapedReviewer2 <- scrapeNodes("span.a-profile-name")
      scrapedReviewer2 <- scrapedReviewer2[1:10]

      
      scrapedReview2 <- scrapeNodes("span.a-size-base.review-text.review-text-content")
      scrapedReview2 <- scrapedReview2[1:10]

      
      scrapedDate2 <- scrapeNodes("span.a-size-base.a-color-secondary.review-date")
      scrapedDate2 <- scrapedDate2[1:10]

      
      scrapedprodRating2 <- scrapeNodes("span.a-icon-alt")
      scrapedprodRating2 <- scrapedprodRating2[1:10]

      
      product2 <- rbind(product2, data.frame(category = scrapedCategory ,name = scrapedprodName,
                          reviewer = scrapedReviewer2,
                          review = scrapedReview2,
                          date = scrapedDate2,
                         ratings = scrapedprodRating2))
```
~~~
```{r}
 link3 = "https://www.amazon.co.uk/Silentnight-Just-Like-Microfibre-Pillow/product-reviews/B00X5YGZMU/ref=cm_cr_getr_d_paging_btm_next_3?ie=UTF8&reviewerType=all_reviews&pageNumber=3"
  
  sessionProd3 <- bow(link3,
               user_agent = "For Educational Purpose")


      
      scrapedReviewer3 <- scrapeNodes("span.a-profile-name")
      scrapedReviewer3 <- scrapedReviewer3[1:10]

      
      scrapedReview3 <- scrapeNodes("span.a-size-base.review-text.review-text-content")
      scrapedReview3 <- scrapedReview3[1:10]

      
      scrapedDate3 <- scrapeNodes("span.a-size-base.a-color-secondary.review-date")
      scrapedDate3 <- scrapedDate3[1:10]

      
      scrapedprodRating3 <- scrapeNodes("span.a-icon-alt")
      scrapedprodRating3 <- scrapedprodRating3[1:10]

      
      product2 <- rbind(product2, data.frame(category = scrapedCategory ,name = scrapedprodName,
                          reviewer = scrapedReviewer3,
                          review = scrapedReview3,
                          date = scrapedDate3,
                         ratings = scrapedprodRating3))
      
View(product2)
```
product3
```{r}

library(dplyr)
library(rvest)
library(polite)
library(httr)
library(selectr)

product3 = data.frame()
scrapedCategory <- "Pillows"
```

```{r}
  
  link = "https://www.amazon.co.uk/product-reviews/B01L97Z3V8/ref=acr_search_hist_5?ie=UTF8&filterByStar=five_star&reviewerType=all_reviews#reviews-filter-bar"
  
      sessionProd1 <- bow(link,
               user_agent = "For Educational Purpose")
  
      scrapeNodes <- function(selector){
      scrape(sessionProd1) %>%
        html_nodes(selector) %>%
        html_text(trim = TRUE)
      }
          
      scrapedprodName <- scrapeNodes("h1.a-size-large.a-text-ellipsis")
    
      
      scrapedReviewer <- scrapeNodes("span.a-profile-name")
      scrapedReviewer <- scrapedReviewer[1:10]

      
      scrapedReview <- scrapeNodes("span.a-size-base.review-text.review-text-content")
      scrapedReview <- scrapedReview[1:10]

      
      scrapedDate <- scrapeNodes("span.a-size-base.a-color-secondary.review-date")
      scrapedDate <- scrapedDate[1:10]

      
      scrapedprodRating <- scrapeNodes("span.a-icon-alt")
      scrapedprodRating <- scrapedprodRating[1:10]

      
      product3 <- rbind(product3, data.frame(category = scrapedCategory,name = scrapedprodName,
                          reviewer = scrapedReviewer,
                          review = scrapedReview,
                          date = scrapedDate,
                         ratings = scrapedprodRating))
```

```{r}        
link2 = "https://www.amazon.co.uk/product-reviews/B01L97Z3V8/ref=cm_cr_arp_d_paging_btm_next_2?ie=UTF8&filterByStar=five_star&reviewerType=all_reviews&pageNumber=2#reviews-filter-bar"
  
  sessionProd2 <- bow(link2,
               user_agent = "For Educational Purpose")


      scrapedReviewer2 <- scrapeNodes("span.a-profile-name")
      scrapedReviewer2 <- scrapedReviewer2[1:10]

      
      scrapedReview2 <- scrapeNodes("span.a-size-base.review-text.review-text-content")
      scrapedReview2 <- scrapedReview2[1:10]

      
      scrapedDate2 <- scrapeNodes("span.a-size-base.a-color-secondary.review-date")
      scrapedDate2 <- scrapedDate2[1:10]

      
      scrapedprodRating2 <- scrapeNodes("span.a-icon-alt")
      scrapedprodRating2 <- scrapedprodRating2[1:10]

      
      product3 <- rbind(product3, data.frame(category = scrapedCategory ,name = scrapedprodName,
                          reviewer = scrapedReviewer2,
                          review = scrapedReview2,
                          date = scrapedDate2,
                         ratings = scrapedprodRating2))
```

```{r}
link3 = "https://www.amazon.co.uk/product-reviews/B01L97Z3V8/ref=cm_cr_getr_d_paging_btm_next_3?ie=UTF8&filterByStar=five_star&reviewerType=all_reviews&pageNumber=3#reviews-filter-bar"
  
  sessionProd3 <- bow(link3,
               user_agent = "For Educational Purpose")


      
      scrapedReviewer3 <- scrapeNodes("span.a-profile-name")
      scrapedReviewer3 <- scrapedReviewer3[1:10]

      
      scrapedReview3 <- scrapeNodes("span.a-size-base.review-text.review-text-content")
      scrapedReview3 <- scrapedReview3[1:10]

      
      scrapedDate3 <- scrapeNodes("span.a-size-base.a-color-secondary.review-date")
      scrapedDate3 <- scrapedDate3[1:10]

      
      scrapedprodRating3 <- scrapeNodes("span.a-icon-alt")
      scrapedprodRating3 <- scrapedprodRating3[1:10]

      
      product3 <- rbind(product3, data.frame(category = scrapedCategory ,name = scrapedprodName,
                          reviewer = scrapedReviewer3,
                          review = scrapedReview3,
                          date = scrapedDate3,
                         ratings = scrapedprodRating3))
      
View(product3)
```
product4
```{r}

library(dplyr)
library(rvest)
library(polite)
library(httr)
library(selectr)

product4 = data.frame()
scrapedCategory <- "Pillows"


  link = "https://www.amazon.co.uk/product-reviews/B01CR9IRWY/ref=cm_cr_arp_d_viewopt_sr?ie=UTF8&filterByStar=all_stars&reviewerType=all_reviews&pageNumber=1#reviews-filter-bar"
  
      sessionProd1 <- bow(link,
               user_agent = "For Educational Purpose")
  
      scrapeNodes <- function(selector){
      scrape(sessionProd1) %>%
        html_nodes(selector) %>%
        html_text(trim = TRUE)
      }
          
       scrapedprodName <- scrapeNodes("h1.a-size-large.a-text-ellipsis")
    
      
      scrapedReviewer <- scrapeNodes("span.a-profile-name")
      scrapedReviewer <- scrapedReviewer[1:10]

      
      scrapedReview <- scrapeNodes("span.a-size-base.review-text.review-text-content")
      scrapedReview <- scrapedReview[1:10]

      
      scrapedDate <- scrapeNodes("span.a-size-base.a-color-secondary.review-date")
      scrapedDate <- scrapedDate[1:10]

      
      scrapedprodRating <- scrapeNodes("span.a-icon-alt")
      scrapedprodRating <- scrapedprodRating[1:10]

      
      product4 <- rbind(product4, data.frame(category = scrapedCategory,name = scrapedprodName,
                          reviewer = scrapedReviewer,
                          review = scrapedReview,
                          date = scrapedDate,
                         ratings = scrapedprodRating))
```

```{r}
link2 = "https://www.amazon.co.uk/product-reviews/B01CR9IRWY/ref=cm_cr_getr_d_paging_btm_next_2?ie=UTF8&filterByStar=all_stars&reviewerType=all_reviews&pageNumber=2#reviews-filter-bar"
  
  sessionProd2 <- bow(link2,
               user_agent = "For Educational Purpose")


      scrapedReviewer2 <- scrapeNodes("span.a-profile-name")
      scrapedReviewer2 <- scrapedReviewer2[1:10]

      
      scrapedReview2 <- scrapeNodes("span.a-size-base.review-text.review-text-content")
      scrapedReview2 <- scrapedReview2[1:10]

      
      scrapedDate2 <- scrapeNodes("span.a-size-base.a-color-secondary.review-date")
      scrapedDate2 <- scrapedDate2[1:10]

      
      scrapedprodRating2 <- scrapeNodes("span.a-icon-alt")
      scrapedprodRating2 <- scrapedprodRating2[1:10]

      
      product4 <- rbind(product4, data.frame(category = scrapedCategory ,name = scrapedprodName,
                          reviewer = scrapedReviewer2,
                          review = scrapedReview2,
                          date = scrapedDate2,
                         ratings = scrapedprodRating2))
```      
      
```{r}
    link3 = "https://www.amazon.co.uk/product-reviews/B01CR9IRWY/ref=cm_cr_getr_d_paging_btm_next_3?ie=UTF8&filterByStar=all_stars&reviewerType=all_reviews&pageNumber=3#reviews-filter-bar"
  
  sessionProd3 <- bow(link3,
               user_agent = "For Educational Purpose")


      
      scrapedReviewer3 <- scrapeNodes("span.a-profile-name")
      scrapedReviewer3 <- scrapedReviewer3[1:10]

      
      scrapedReview3 <- scrapeNodes("span.a-size-base.review-text.review-text-content")
      scrapedReview3 <- scrapedReview3[1:10]

      
      scrapedDate3 <- scrapeNodes("span.a-size-base.a-color-secondary.review-date")
      scrapedDate3 <- scrapedDate3[1:10]

      
      scrapedprodRating3 <- scrapeNodes("span.a-icon-alt")
      scrapedprodRating3 <- scrapedprodRating3[1:10]

      
      product4 <- rbind(product4, data.frame(category = scrapedCategory ,name = scrapedprodName,
                          reviewer = scrapedReviewer3,
                          review = scrapedReview3,
                          date = scrapedDate3,
                         ratings = scrapedprodRating3))
      
View(product4)
```
product5
```{r}

library(dplyr)
library(rvest)
library(polite)
library(httr)
library(selectr)

product5 = data.frame()
scrapedCategory <- "Pillows"
```

```{r}
link = "https://www.amazon.co.uk/product-reviews/B086ZCVXKW/ref=cm_cr_arp_d_viewopt_sr?ie=UTF8&filterByStar=all_stars&reviewerType=all_reviews&pageNumber=1#reviews-filter-bar"
  
      sessionProd1 <- bow(link,
               user_agent = "For Educational Purpose")
  
      scrapeNodes <- function(selector){
      scrape(sessionProd1) %>%
        html_nodes(selector) %>%
        html_text(trim = TRUE)
      }
          
      scrapedprodName <- scrapeNodes("h1.a-size-large.a-text-ellipsis")
    
      
      scrapedReviewer <- scrapeNodes("span.a-profile-name")
      scrapedReviewer <- scrapedReviewer[1:10]

      
      scrapedReview <- scrapeNodes("span.a-size-base.review-text.review-text-content")
      scrapedReview <- scrapedReview[1:10]

      
      scrapedDate <- scrapeNodes("span.a-size-base.a-color-secondary.review-date")
      scrapedDate <- scrapedDate[1:10]

      
      scrapedprodRating <- scrapeNodes("span.a-icon-alt")
      scrapedprodRating <- scrapedprodRating[1:10]

      
      product5 <- rbind(product5, data.frame(category = scrapedCategory,name = scrapedprodName,
                          reviewer = scrapedReviewer,
                          review = scrapedReview,
                          date = scrapedDate,
                         ratings = scrapedprodRating))
```

```{r}
link2 = "https://www.amazon.co.uk/product-reviews/B086ZCVXKW/ref=cm_cr_getr_d_paging_btm_next_2?ie=UTF8&filterByStar=all_stars&reviewerType=all_reviews&pageNumber=2#reviews-filter-bar"
  
  sessionProd2 <- bow(link2,
               user_agent = "For Educational Purpose")


      scrapedReviewer2 <- scrapeNodes("span.a-profile-name")
      scrapedReviewer2 <- scrapedReviewer2[1:10]

      
      scrapedReview2 <- scrapeNodes("span.a-size-base.review-text.review-text-content")
      scrapedReview2 <- scrapedReview2[1:10]

      
      scrapedDate2 <- scrapeNodes("span.a-size-base.a-color-secondary.review-date")
      scrapedDate2 <- scrapedDate2[1:10]

      
      scrapedprodRating2 <- scrapeNodes("span.a-icon-alt")
      scrapedprodRating2 <- scrapedprodRating2[1:10]

      
      product5 <- rbind(product5, data.frame(category = scrapedCategory ,name = scrapedprodName,
                          reviewer = scrapedReviewer2,
                          review = scrapedReview2,
                          date = scrapedDate2,
                         ratings = scrapedprodRating2))
      
      
```

```{r}
link3 = "https://www.amazon.co.uk/product-reviews/B086ZCVXKW/ref=cm_cr_getr_d_paging_btm_next_3?ie=UTF8&filterByStar=all_stars&reviewerType=all_reviews&pageNumber=3#reviews-filter-bar"
  
  sessionProd3 <- bow(link3,
               user_agent = "For Educational Purpose")


      
      scrapedReviewer3 <- scrapeNodes("span.a-profile-name")
      scrapedReviewer3 <- scrapedReviewer3[1:10]

      
      scrapedReview3 <- scrapeNodes("span.a-size-base.review-text.review-text-content")
      scrapedReview3 <- scrapedReview3[1:10]

      
      scrapedDate3 <- scrapeNodes("span.a-size-base.a-color-secondary.review-date")
      scrapedDate3 <- scrapedDate3[1:10]

      
      scrapedprodRating3 <- scrapeNodes("span.a-icon-alt")
      scrapedprodRating3 <- scrapedprodRating3[1:10]

      
      product5 <- rbind(product5, data.frame(category = scrapedCategory ,name = scrapedprodName,
                          reviewer = scrapedReviewer3,
                          review = scrapedReview3,
                          date = scrapedDate3,
                         ratings = scrapedprodRating3))
      
View(product5)
```
product6
```{r}

library(dplyr)
library(rvest)
library(polite)
library(httr)
library(selectr)

product6 = data.frame()
scrapedCategory <- "Socks"
```

```{r}
link = "https://www.amazon.co.uk/product-reviews/B07FCCT5QW/ref=cm_cr_arp_d_viewopt_sr?ie=UTF8&filterByStar=all_stars&reviewerType=all_reviews&pageNumber=1#reviews-filter-bar"
  
      sessionProd1 <- bow(link,
               user_agent = "For Educational Purpose")
  
      scrapeNodes <- function(selector){
      scrape(sessionProd1) %>%
        html_nodes(selector) %>%
        html_text(trim = TRUE)
      }
          
      scrapedprodName <- scrapeNodes("h1.a-size-large.a-text-ellipsis")
    
      
      scrapedReviewer <- scrapeNodes("span.a-profile-name")
      scrapedReviewer <- scrapedReviewer[1:10]

      
      scrapedReview <- scrapeNodes("span.a-size-base.review-text.review-text-content")
      scrapedReview <- scrapedReview[1:10]

      
      scrapedDate <- scrapeNodes("span.a-size-base.a-color-secondary.review-date")
      scrapedDate <- scrapedDate[1:10]

      
      scrapedprodRating <- scrapeNodes("span.a-icon-alt")
      scrapedprodRating <- scrapedprodRating[1:10]

      
      product6 <- rbind(product6, data.frame(category = scrapedCategory,name = scrapedprodName,
                          reviewer = scrapedReviewer,
                          review = scrapedReview,
                          date = scrapedDate,
                         ratings = scrapedprodRating))
```

```{r}
link2 = "https://www.amazon.co.uk/product-reviews/B07FCCT5QW/ref=cm_cr_getr_d_paging_btm_next_2?ie=UTF8&filterByStar=all_stars&reviewerType=all_reviews&pageNumber=2#reviews-filter-bar"
  
  sessionProd2 <- bow(link2,
               user_agent = "For Educational Purpose")


      scrapedReviewer2 <- scrapeNodes("span.a-profile-name")
      scrapedReviewer2 <- scrapedReviewer2[1:10]

      
      scrapedReview2 <- scrapeNodes("span.a-size-base.review-text.review-text-content")
      scrapedReview2 <- scrapedReview2[1:10]

      
      scrapedDate2 <- scrapeNodes("span.a-size-base.a-color-secondary.review-date")
      scrapedDate2 <- scrapedDate2[1:10]

      
      scrapedprodRating2 <- scrapeNodes("span.a-icon-alt")
      scrapedprodRating2 <- scrapedprodRating2[1:10]

      
      product6 <- rbind(product6, data.frame(category = scrapedCategory ,name = scrapedprodName,
                          reviewer = scrapedReviewer2,
                          review = scrapedReview2,
                          date = scrapedDate2,
                         ratings = scrapedprodRating2))
```

```{r}
link3 = "https://www.amazon.co.uk/product-reviews/B07FCCT5QW/ref=cm_cr_getr_d_paging_btm_next_3?ie=UTF8&filterByStar=all_stars&reviewerType=all_reviews&pageNumber=3#reviews-filter-bar"
  
  sessionProd3 <- bow(link3,
               user_agent = "For Educational Purpose")


      
      scrapedReviewer3 <- scrapeNodes("span.a-profile-name")
      scrapedReviewer3 <- scrapedReviewer3[1:10]

      
      scrapedReview3 <- scrapeNodes("span.a-size-base.review-text.review-text-content")
      scrapedReview3 <- scrapedReview3[1:10]

      
      scrapedDate3 <- scrapeNodes("span.a-size-base.a-color-secondary.review-date")
      scrapedDate3 <- scrapedDate3[1:10]

      
      scrapedprodRating3 <- scrapeNodes("span.a-icon-alt")
      scrapedprodRating3 <- scrapedprodRating3[1:10]

      
      product6 <- rbind(product6, data.frame(category = scrapedCategory ,name = scrapedprodName,
                          reviewer = scrapedReviewer3,
                          review = scrapedReview3,
                          date = scrapedDate3,
                         ratings = scrapedprodRating3))
      
View(product6)
```
product7
```{r}

library(dplyr)
library(rvest)
library(polite)
library(httr)
library(selectr)

product7 = data.frame()
scrapedCategory <- "Socks"
```

```{r}
link = "https://www.amazon.co.uk/product-reviews/B013IADXR0/ref=cm_cr_arp_d_viewopt_sr?ie=UTF8&filterByStar=all_stars&reviewerType=all_reviews&pageNumber=1#reviews-filter-bar"
  
      sessionProd1 <- bow(link,
               user_agent = "For Educational Purpose")
  
      scrapeNodes <- function(selector){
      scrape(sessionProd1) %>%
        html_nodes(selector) %>%
        html_text(trim = TRUE)
      }
          
      scrapedprodName <- scrapeNodes("h1.a-size-large.a-text-ellipsis")
    
      
      scrapedReviewer <- scrapeNodes("span.a-profile-name")
      scrapedReviewer <- scrapedReviewer[1:10]

      
      scrapedReview <- scrapeNodes("span.a-size-base.review-text.review-text-content")
      scrapedReview <- scrapedReview[1:10]

      
      scrapedDate <- scrapeNodes("span.a-size-base.a-color-secondary.review-date")
      scrapedDate <- scrapedDate[1:10]

      
      scrapedprodRating <- scrapeNodes("span.a-icon-alt")
      scrapedprodRating <- scrapedprodRating[1:10]

      
      product7 <- rbind(product7, data.frame(category = scrapedCategory,name = scrapedprodName,
                          reviewer = scrapedReviewer,
                          review = scrapedReview,
                          date = scrapedDate,
                         ratings = scrapedprodRating))
```

```{r}
link2 = "https://www.amazon.co.uk/product-reviews/B013IADXR0/ref=cm_cr_getr_d_paging_btm_next_2?ie=UTF8&filterByStar=all_stars&reviewerType=all_reviews&pageNumber=2#reviews-filter-bar"
  
  sessionProd2 <- bow(link2,
               user_agent = "For Educational Purpose")


      scrapedReviewer2 <- scrapeNodes("span.a-profile-name")
      scrapedReviewer2 <- scrapedReviewer2[1:10]

      
      scrapedReview2 <- scrapeNodes("span.a-size-base.review-text.review-text-content")
      scrapedReview2 <- scrapedReview2[1:10]

      
      scrapedDate2 <- scrapeNodes("span.a-size-base.a-color-secondary.review-date")
      scrapedDate2 <- scrapedDate2[1:10]

      
      scrapedprodRating2 <- scrapeNodes("span.a-icon-alt")
      scrapedprodRating2 <- scrapedprodRating2[1:10]

      
      product7 <- rbind(product7, data.frame(category = scrapedCategory ,name = scrapedprodName,
                          reviewer = scrapedReviewer2,
                          review = scrapedReview2,
                          date = scrapedDate2,
                         ratings = scrapedprodRating2))
      
      
```

```{r}
link3 = "https://www.amazon.co.uk/product-reviews/B013IADXR0/ref=cm_cr_getr_d_paging_btm_next_3?ie=UTF8&filterByStar=all_stars&reviewerType=all_reviews&pageNumber=3#reviews-filter-bar"
  
  sessionProd3 <- bow(link3,
               user_agent = "For Educational Purpose")


      
      scrapedReviewer3 <- scrapeNodes("span.a-profile-name")
      scrapedReviewer3 <- scrapedReviewer3[1:10]

      
      scrapedReview3 <- scrapeNodes("span.a-size-base.review-text.review-text-content")
      scrapedReview3 <- scrapedReview3[1:10]

      
      scrapedDate3 <- scrapeNodes("span.a-size-base.a-color-secondary.review-date")
      scrapedDate3 <- scrapedDate3[1:10]

      
      scrapedprodRating3 <- scrapeNodes("span.a-icon-alt")
      scrapedprodRating3 <- scrapedprodRating3[1:10]

      
      product7 <- rbind(product7, data.frame(category = scrapedCategory ,name = scrapedprodName,
                          reviewer = scrapedReviewer3,
                          review = scrapedReview3,
                          date = scrapedDate3,
                         ratings = scrapedprodRating3))
      
View(product7)
```
product8
```{r}

library(dplyr)
library(rvest)
library(polite)
library(httr)
library(selectr)

product8 = data.frame()
scrapedCategory <- "Socks"
```

```{r}
link = "https://www.amazon.co.uk/product-reviews/B0150BE59U/ref=cm_cr_arp_d_viewopt_sr?ie=UTF8&filterByStar=all_stars&reviewerType=all_reviews&pageNumber=1#reviews-filter-bar"
  
      sessionProd1 <- bow(link,
               user_agent = "For Educational Purpose")
  
      scrapeNodes <- function(selector){
      scrape(sessionProd1) %>%
        html_nodes(selector) %>%
        html_text(trim = TRUE)
      }
          
      scrapedprodName <- scrapeNodes("h1.a-size-large.a-text-ellipsis")
    
      
      scrapedReviewer <- scrapeNodes("span.a-profile-name")
      scrapedReviewer <- scrapedReviewer[1:10]

      
      scrapedReview <- scrapeNodes("span.a-size-base.review-text.review-text-content")
      scrapedReview <- scrapedReview[1:10]

      
      scrapedDate <- scrapeNodes("span.a-size-base.a-color-secondary.review-date")
      scrapedDate <- scrapedDate[1:10]

      
      scrapedprodRating <- scrapeNodes("span.a-icon-alt")
      scrapedprodRating <- scrapedprodRating[1:10]

      
      product8 <- rbind(product8, data.frame(category = scrapedCategory,name = scrapedprodName,
                          reviewer = scrapedReviewer,
                          review = scrapedReview,
                          date = scrapedDate,
                         ratings = scrapedprodRating))
```

```{r}
link2 = "https://www.amazon.co.uk/product-reviews/B0150BE59U/ref=cm_cr_arp_d_paging_btm_next_2?ie=UTF8&filterByStar=all_stars&reviewerType=all_reviews&pageNumber=2#reviews-filter-bar"
  
  sessionProd2 <- bow(link2,
               user_agent = "For Educational Purpose")


      scrapedReviewer2 <- scrapeNodes("span.a-profile-name")
      scrapedReviewer2 <- scrapedReviewer2[1:10]

      
      scrapedReview2 <- scrapeNodes("span.a-size-base.review-text.review-text-content")
      scrapedReview2 <- scrapedReview2[1:10]

      
      scrapedDate2 <- scrapeNodes("span.a-size-base.a-color-secondary.review-date")
      scrapedDate2 <- scrapedDate2[1:10]

      
      scrapedprodRating2 <- scrapeNodes("span.a-icon-alt")
      scrapedprodRating2 <- scrapedprodRating2[1:10]

      
      product8 <- rbind(product8, data.frame(category = scrapedCategory ,name = scrapedprodName,
                          reviewer = scrapedReviewer2,
                          review = scrapedReview2,
                          date = scrapedDate2,
                         ratings = scrapedprodRating2))
```

```{r}
link3 = "https://www.amazon.co.uk/product-reviews/B0150BE59U/ref=cm_cr_getr_d_paging_btm_next_3?ie=UTF8&filterByStar=all_stars&reviewerType=all_reviews&pageNumber=3#reviews-filter-bar"
  
  sessionProd3 <- bow(link3,
               user_agent = "For Educational Purpose")


      
      scrapedReviewer3 <- scrapeNodes("span.a-profile-name")
      scrapedReviewer3 <- scrapedReviewer3[1:10]

      
      scrapedReview3 <- scrapeNodes("span.a-size-base.review-text.review-text-content")
      scrapedReview3 <- scrapedReview3[1:10]

      
      scrapedDate3 <- scrapeNodes("span.a-size-base.a-color-secondary.review-date")
      scrapedDate3 <- scrapedDate3[1:10]

      
      scrapedprodRating3 <- scrapeNodes("span.a-icon-alt")
      scrapedprodRating3 <- scrapedprodRating3[1:10]

      
      product8 <- rbind(product8, data.frame(category = scrapedCategory ,name = scrapedprodName,
                          reviewer = scrapedReviewer3,
                          review = scrapedReview3,
                          date = scrapedDate3,
                         ratings = scrapedprodRating3))
      
View(product8)
```
product9
```{r}

library(dplyr)
library(rvest)
library(polite)
library(httr)
library(selectr)

product9 = data.frame()
scrapedCategory <- "Socks"
```

```{r}
link = "https://www.amazon.co.uk/product-reviews/B07VSQ7GR2/ref=cm_cr_arp_d_viewopt_sr?ie=UTF8&filterByStar=all_stars&reviewerType=all_reviews&pageNumber=1#reviews-filter-bar"
  
      sessionProd1 <- bow(link,
               user_agent = "For Educational Purpose")
  
      scrapeNodes <- function(selector){
      scrape(sessionProd1) %>%
        html_nodes(selector) %>%
        html_text(trim = TRUE)
      }
          
      scrapedprodName <- scrapeNodes("h1.a-size-large.a-text-ellipsis")
    
      
      scrapedReviewer <- scrapeNodes("span.a-profile-name")
      scrapedReviewer <- scrapedReviewer[1:10]

      
      scrapedReview <- scrapeNodes("span.a-size-base.review-text.review-text-content")
      scrapedReview <- scrapedReview[1:10]

      
      scrapedDate <- scrapeNodes("span.a-size-base.a-color-secondary.review-date")
      scrapedDate <- scrapedDate[1:10]

      
      scrapedprodRating <- scrapeNodes("span.a-icon-alt")
      scrapedprodRating <- scrapedprodRating[1:10]

      
      product9 <- rbind(product9, data.frame(category = scrapedCategory,name = scrapedprodName,
                          reviewer = scrapedReviewer,
                          review = scrapedReview,
                          date = scrapedDate,
                         ratings = scrapedprodRating))
```

```{r}
link2 = "https://www.amazon.co.uk/product-reviews/B07VSQ7GR2/ref=cm_cr_getr_d_paging_btm_next_2?ie=UTF8&filterByStar=all_stars&reviewerType=all_reviews&pageNumber=2#reviews-filter-bar"
  
  sessionProd2 <- bow(link2,
               user_agent = "For Educational Purpose")


      scrapedReviewer2 <- scrapeNodes("span.a-profile-name")
      scrapedReviewer2 <- scrapedReviewer2[1:10]

      
      scrapedReview2 <- scrapeNodes("span.a-size-base.review-text.review-text-content")
      scrapedReview2 <- scrapedReview2[1:10]

      
      scrapedDate2 <- scrapeNodes("span.a-size-base.a-color-secondary.review-date")
      scrapedDate2 <- scrapedDate2[1:10]

      
      scrapedprodRating2 <- scrapeNodes("span.a-icon-alt")
      scrapedprodRating2 <- scrapedprodRating2[1:10]

      
      product9 <- rbind(product9, data.frame(category = scrapedCategory ,name = scrapedprodName,
                          reviewer = scrapedReviewer2,
                          review = scrapedReview2,
                          date = scrapedDate2,
                         ratings = scrapedprodRating2))
```

```{r}
link3 = "https://www.amazon.co.uk/product-reviews/B07VSQ7GR2/ref=cm_cr_getr_d_paging_btm_next_3?ie=UTF8&filterByStar=all_stars&reviewerType=all_reviews&pageNumber=3#reviews-filter-bar"
  
  sessionProd3 <- bow(link3,
               user_agent = "For Educational Purpose")


      
      scrapedReviewer3 <- scrapeNodes("span.a-profile-name")
      scrapedReviewer3 <- scrapedReviewer3[1:10]

      
      scrapedReview3 <- scrapeNodes("span.a-size-base.review-text.review-text-content")
      scrapedReview3 <- scrapedReview3[1:10]

      
      scrapedDate3 <- scrapeNodes("span.a-size-base.a-color-secondary.review-date")
      scrapedDate3 <- scrapedDate3[1:10]

      
      scrapedprodRating3 <- scrapeNodes("span.a-icon-alt")
      scrapedprodRating3 <- scrapedprodRating3[1:10]

      
      product9 <- rbind(product9, data.frame(category = scrapedCategory ,name = scrapedprodName,
                          reviewer = scrapedReviewer3,
                          review = scrapedReview3,
                          date = scrapedDate3,
                          ratings = scrapedprodRating3))
      
View(product9)
```
product10
```{r}

library(dplyr)
library(rvest)
library(polite)
library(httr)
library(selectr)

product10 = data.frame()
scrapedCategory <- "Socks"
```

```{r}
link = "https://www.amazon.co.uk/product-reviews/B0150BE59U/ref=cm_cr_arp_d_viewopt_sr?ie=UTF8&filterByStar=all_stars&reviewerType=all_reviews&pageNumber=1#reviews-filter-bar"
  
      sessionProd1 <- bow(link,
               user_agent = "For Educational Purpose")
  
      scrapeNodes <- function(selector){
      scrape(sessionProd1) %>%
        html_nodes(selector) %>%
        html_text(trim = TRUE)
      }
          
      scrapedprodName <- scrapeNodes("h1.a-size-large.a-text-ellipsis")
    
      
      scrapedReviewer <- scrapeNodes("span.a-profile-name")
      scrapedReviewer <- scrapedReviewer[1:10]

      
      scrapedReview <- scrapeNodes("span.a-size-base.review-text.review-text-content")
      scrapedReview <- scrapedReview[1:10]

      
      scrapedDate <- scrapeNodes("span.a-size-base.a-color-secondary.review-date")
      scrapedDate <- scrapedDate[1:10]

      
      scrapedprodRating <- scrapeNodes("span.a-icon-alt")
      scrapedprodRating <- scrapedprodRating[1:10]

      
      product10 <- rbind(product10, data.frame(category = scrapedCategory,name = scrapedprodName,
                          reviewer = scrapedReviewer,
                          review = scrapedReview,
                          date = scrapedDate,
                         ratings = scrapedprodRating))
```

```{r}
link2 = "https://www.amazon.co.uk/product-reviews/B0150BE59U/ref=cm_cr_getr_d_paging_btm_next_2?ie=UTF8&filterByStar=all_stars&reviewerType=all_reviews&pageNumber=2#reviews-filter-bar"
  
  sessionProd2 <- bow(link2,
               user_agent = "For Educational Purpose")


      scrapedReviewer2 <- scrapeNodes("span.a-profile-name")
      scrapedReviewer2 <- scrapedReviewer2[1:10]

      
      scrapedReview2 <- scrapeNodes("span.a-size-base.review-text.review-text-content")
      scrapedReview2 <- scrapedReview2[1:10]

      
      scrapedDate2 <- scrapeNodes("span.a-size-base.a-color-secondary.review-date")
      scrapedDate2 <- scrapedDate2[1:10]

      
      scrapedprodRating2 <- scrapeNodes("span.a-icon-alt")
      scrapedprodRating2 <- scrapedprodRating2[1:10]

      
      product10 <- rbind(product10, data.frame(category = scrapedCategory ,name = scrapedprodName,
                          reviewer = scrapedReviewer2,
                          review = scrapedReview2,
                          date = scrapedDate2,
                         ratings = scrapedprodRating2))
```

```{r}
link3 = "https://www.amazon.co.uk/product-reviews/B0150BE59U/ref=cm_cr_getr_d_paging_btm_next_3?ie=UTF8&filterByStar=all_stars&reviewerType=all_reviews&pageNumber=3#reviews-filter-bar"
  
  sessionProd3 <- bow(link3,
               user_agent = "For Educational Purpose")


      
      scrapedReviewer3 <- scrapeNodes("span.a-profile-name")
      scrapedReviewer3 <- scrapedReviewer3[1:10]

      
      scrapedReview3 <- scrapeNodes("span.a-size-base.review-text.review-text-content")
      scrapedReview3 <- scrapedReview3[1:10]

      
      scrapedDate3 <- scrapeNodes("span.a-size-base.a-color-secondary.review-date")
      scrapedDate3 <- scrapedDate3[1:10]

      
      scrapedprodRating3 <- scrapeNodes("span.a-icon-alt")
      scrapedprodRating3 <- scrapedprodRating3[1:10]

      
      product10 <- rbind(product10, data.frame(category = scrapedCategory ,name = scrapedprodName,
                          reviewer = scrapedReviewer3,
                          review = scrapedReview3,
                          date = scrapedDate3,
                         ratings = scrapedprodRating3))
      
View(product10)
```

```{r}

all_reviews <- rbind(product1, product2, product3, product4, product5, product6, product7, product8, product9, product10)
View(all_reviews)

#install.packages("usethis")
library(usethis)
```
